### ISSUE TITLE
Would it be possible to lower friendsofphp/php-cs-fixer version requirement to v3.4 for drupal/core-recommended:^9.x to work with it (on a specific version, eg: 0.3.9)

### ISSUE THREAD

**Issue by eedev** [elyby/php-code-style#15]
Hello there 👋 

I'm sorry to trouble you again! 

I need to use your project with Drupal 9 but, the friendsofphp/php-cs-fixer:^3.11 requirement that was introduced a few days before your 0.4.0 release is not compatible with Drupal 9. 

This is because drupal/core-recommended:^9.0 (until ^10.0) depends on `symfony/console: ~v4.4.49`, while `friendsofphp/php-cs-fixer:^3.11` requires `symfony/console: ^5.4 || ^6.0`.

Although [symfony/console](https://packagist.org/packages/symfony/console):`^4.4.20 || ^5.1.3 || ^6.0` was suitable for https://packagist.org/packages/friendsofphp/php-cs-fixer#v3.4.0, it is no longer compatible with https://packagist.org/packages/friendsofphp/php-cs-fixer#v3.5.0.

Would it be feasible go back in time and to create a tag, maybe something like 0.3.9 using friendsofphp/php-cs-fixer:^3.4 required ?

Thank you for your assistance 😄 .

**Comment by erickskrauch** [comment]
Do you want to use our entire codestyle or just custom rules?

**Comment by eedev** [comment]
This is what I use : 

```yaml
parameters:
  rules:
    Drupal/blank_line_before_end_of_class: false
    Ely/blank_line_around_class_body: true
    Ely/blank_line_before_return: true
    Ely/line_break_after_statements: true
```
